export const FETCH_POSTS = 'FETCH_POSTS';  
export const FETCH_CONTACT = 'FETCH_CONTACT';  
export const FETCH_CLIENTS = 'FETCH_CLIENTS';  
export const FETCH_CLIENTSLIST = 'FETCH_CLIENTSLIST';
export const FETCH_EVENTLIST = 'FETCH_EVENTLIST';
export const FETCH_EVENTDETAIL = 'FETCH_EVENTDETAIL';
export const FETCH_ALBUMS = 'FETCH_ALBUMS';
export const FETCH_ALBUMSDETAILS = 'FETCH_ALBUMSDETAILS';
export const FETCH_BANNER = 'FETCH_BANNER';
export const FETCH_WHO_WEW_ARE = 'FETCH_WHO_WEW_ARE';
export const FETCH_GALLERYCATEGORY = 'FETCH_GALLERYCATEGORY';
export const FETCH_STORELIST = 'FETCH_STORELIST';
export const FETCH_STOREDETAILS = 'FETCH_STOREDETAILS';
export const FETCH_STORECATEGORY = 'FETCH_STORECATEGORY';
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const ADD_CART = 'ADD_CART';
export const GET_CART = 'GET_CART';
export const DELETE_CART = 'DELETE_CART';
export const FETCH_EVENTTICKET = 'FETCH_EVENTTICKET';


